# docker-compose for real, production deployments of the production image.
# You will have to create common-with-passwords.env from common.env in the
# obvious way.

version: '3.2'
services:
  frontend:
    image: pcic/pdp:latest
    container_name: pdp_frontend
    env_file:
      - common-with-passwords.env
    environment:
      # Specific to frontend
      - APP_ROOT=https://services.pacificclimate.org/dataportal/
      - DATA_ROOT=https://services.pacificclimate.org/dataportal/data
      - APP_MODULE=pdp.wsgi:frontend
      - GEOSERVER_URL=https://tools.pacificclimate.org/geoserver/
      - NCWMS_URL=NCWMS_URL=https://services.pacificclimate.org/ncwms-mm-rproxy/dynamic/x
      - OLD_NCWMS_URL=https://services.pacificclimate.org/ncWMS-PCIC/wms
      - TILES_URL=https://services.pacificclimate.org/tiles
    ports:
      - "8000:8000"  # frontend
    volumes:
      - type: bind
        source: /storage/data/projects/comp_support/pdp/docker-prod/prism_demo_config.js
        target: /opt/dockeragent/pdp/static/js/prism_demo_config.js

  backend:
    image: pcic/pdp:latest
    container_name: pdp_backend
    env_file:
      - common-with-passwords.env
    environment:
      # Specific to backend
      - APP_MODULE=pdp.wsgi:backend
      - GUNICORN_WORKER_CLASS=gevent
    ports:
      - "8001:8000"  # backend
    depends_on:
      - "pgbouncer"
    volumes:
      - /storage/data/climate/downscale:/storage/data/climate/downscale:ro
      - /storage/data/climate/hydrology:/storage/data/climate/hydrology:ro
      - /storage/data/climate/observations:/storage/data/climate/observations:ro
      - /storage/data/climate/PRISM:/storage/data/climate/PRISM:ro
      - /storage/data/projects/dataportal:/storage/data/projects/dataportal:ro
      - /storage/data/projects/hydrology:/storage/data/projects/hydrology:ro
      - /storage/data/projects/PRISM:/storage/data/projects/PRISM:ro

  pgbouncer:
    image: edoburu/pgbouncer
    container_name: pgbouncer
    volumes:
      - ./pgbounce_users.txt:/etc/pgbouncer/userlist.txt:ro
      - ./pgbouncer.ini:/etc/pgbouncer/pgbouncer.ini:ro


