version: '2'
services:
  frontend:
    image: pcic/pdp:latest
    container_name: pdp_frontend
    ports:
      - "8000:8000"  # frontend
    env_file:
      - fe_deployment.env

  backend:
    image: pcic/pdp:latest
    container_name: pdp_backend
    env_file:
      - be_deployment.env
    ports:
      - "8001:8000"  # backend

    volumes_from:
      - container:pdp_data:ro
