name: Python CI

on: push

jobs:
  test:

    runs-on: self-hosted
    strategy:
      matrix:
        python-version: [2.7]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      env:
        PIP_INDEX_URL: https://pypi.pacificclimate.org/simple
        CPLUS_INCLUDE_PATH: /usr/include/gdal
        C_INCLUDE_PATH: /usr/include/gdal
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc libhdf5-dev libnetcdf-dev libgdal-dev python-dev python-pip build-essential git
        pip install -U pip pytest setuptools wheel
        echo '### intalling numpy, Cython, gdal'
        pip install --no-binary :all: numpy Cython==0.22 gdal==2.2
        echo '### numpy, Cython, gdal installed'
        echo '### intalling h5py, requirements*.txt'
        pip install --no-binary h5py -r requirements.txt -r test_requirements.txt
        echo '### h5py, requirements*.txt installed'
        pip install sphinx
        echo '### installing .'
        pip install .
        echo '### . installed'
    - name: Test with pytest
      env:
        DSN: ${{ secrets.DSN_PCIC_META_TEST }}
      run: |
        py.test -m "not local_only" -v --tb=short
