name: Python CI

on: push

jobs:
  build-image:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@master

      - name: Publish to Registry
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.pcicdevops_at_dockerhub_username }}
          password: ${{ secrets.pcicdevops_at_dockerhub_password }}
          dockerfile: ./docker/ci/Dockerfile
          repository: pcic/pdp-ci
          tags: latest

  run-tests:
    runs-on: ubuntu-18.04
    needs: build-image
    container:
      # Built in step above
      image: pcic/pdp-ci:latest

    steps:
    - name: Test with pytest
      env:
        DSN: ${{ secrets.DSN_PCIC_META_TEST }}
      run: |
        echo id: $(id)
        echo pwd: $(pwd)
        ls -la
        echo 'PATH=' $PATH
        python --version
        which python
        cd ${USER_DIR}
        echo 'PYTHONPATH=' $PYTHONPATH
        python -c 'import sys; print "\n".join(sys.path)'
        echo "after install"
        pip freeze
        pydoc modules
        python -m pytest -m "not local_only" -v --tb=short
