name: Python CI

on: push

jobs:
  # TODO: Either figure out how to do without this auxiliary container,
  #   or use workflow caching to avoid rebuilding this image each time.
  build-image:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@master

      - name: Publish to Registry
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.pcicdevops_at_dockerhub_username }}
          password: ${{ secrets.pcicdevops_at_dockerhub_password }}
          dockerfile: ./docker/ci/Dockerfile
          repository: pcic/pdp-ci
          tags: latest

  run-tests:
    runs-on: ubuntu-18.04
    needs: build-image
    container:
      # Built in step above
      image: pcic/pdp-ci:latest

    steps:
    - name: Test with pytest
      run: |
        cd ${USER_DIR}  # Necessary because GitHub sets a weird pwd
        pytest -m "not local_only and not crmpdb and not bulk_data" -v --tb=short tests/
